### ISSUE TITLE
Invalid href

### ISSUE THREAD

**Issue by JAPA-Gerthner** [Rongrat/site#2]
Always place atleast something to the href attribute
If you have nothing to place - just moch it with "#" lite at following code
<a href="#">Some Stuff</a>

Otherwise like wouldnt be rendered as link (highlited by blue and stuff...)

https://github.com/Rongrat/site/blob/c38a461736f2038a1e103e7708cb4637f9c4d4bb/fg.html#L10

**Comment by Rongrat** [comment]
https://github.com/Rongrat/site/commit/7bfad0bdad29e897dd9b0f05dbf21a2a03b13547

**Comment by JAPA-Gerthner** [comment]
Its OK for now

Thanks,
Keep pushing
